from fuzzywuzzy import fuzz
from fuzzywuzzy import process

choices = ['battery untill', 'looks', 'touch', 'speed', 'issues', 'dont', 'update', 'situations', 'window', 'winner', 'ram management', 'feel', 'charge', 'condition', 'usage', 'camera quality', 'cool', 'damages', 'dad', 'case', 'smartphone', 'cool cam', 'advantage', 'views', 'awsome', 'game', 'bilion day', 'fingerprint', 'front', 'bit', 'day', 'color', 'disply', 'similar', 'signal reception', 'quality game', 'quality mobile', 'signal', 'brightness', 'item', 'honor', 'emui', 'mode', 'output', 'memory bt', 'flipkart', 'mode picture', 'deal', 'people', 'branding', 'product worth', 'salot', 'noise', 'design', 'honor mobile', 'build quality', 'review', 'power savng', 'aperture mode', 'speaker audio', 'everything', 'finger', 'avenues', 'sensor', 'camera amazing', 'satisfy', 'camera clarity', 'amazon', 'power', 'use granuels', 'confusion', 'screen', 'thanks', 'use', 'update', 'efficiency', 'packing', 'slim', 'price fluctuation', 'sensors', 'bilion', 'super', 'front camera', 'heating', 'experience', 'amount', 'backup', 'processor', 'software', 'load', 'features', 'criterias', 'battery', 'image', 'batry', 'dont use', 'everyone', 'delevery', 'shoots', 'quality', 'story', 'management', 'service', 'usage i', 'look cons', 'fast', 'battery backup', 'camera', 'criteria', 'aperture', 'batrry', 'mobiles', 'function', 'cricket', 'buy', 'brand', 'memory', 'phone look', 'delivery', 'phone', 'part', 'quality honor', 'product value', 'sound', 'look', 'camera cons', 'advantage charging', 'mobile', 'louder', 'ui', 'today', 'cam', 'problem', 'piece', 'display', 'camara', 'compare', 'earphone', 'lines', 'ram', 'censor', 'life', 'camera awesome', 'phone battery', 'work', 'technology', 'guarantee', 'make', 'get', 'nd', 'feature', 'note', 'amazing', 'speaker', 'build', 'speed network', 'performance', 'android', 'charging', 'sim', 'product', 'okay', 'phn', 'though', 'price', 'hang', 'effect', 'jst', 'thank you', 'battery life', 'device', 'mah', 'data', 'response', 'feature s', 'purchase', 'calls', 'light', 'colour', 'super mobile', 'options', 'phone value', 'con', 'reception', 'time', 'rupees', 'notch']

i=0
for choice in choices[:-1]:
	print "comparing similarity of: "+choice
	print process.extract(choice, choices[i+1:],limit = len(choices) - i-1)
	i += 1