scrapy crawl searchspiderflipkart
scrapy crawl completeflipkartscraper -o flipkartreviews.json
scrapy crawl searchspideramazon
scrapy crawl getproductspideramazon
scrapy crawl completeamazonscraper -o amazonreviews.json